name: 'test_source_changes'

config-version: 2
version: '0.1'

profile: 'test_source_changes'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  test_source_changes:
      materialized: table
      staging:
        materialized: view
