config-version: 2


name: source_config_project
profile: source_config_project

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

seeds:
  localdep:
    enabled: true
    keep:
      enabled: true
  quote_columns: false
sources:
  localdep:
    my_other_source:
      enabled: true

# list of eventually available source config options
# enabled: True,
# quoting:
#     database: False
#     schema: False
#     identifier: False
#     column: False
# freshness:
#     error_after: {count: 24, period: hour}
#     warn_after: {count: 12, period: hour}
# loader: "a_loader"
# loaded_at_field: some_column
# database: custom_database
# schema: custom_schema
# # identifier: "seed"  #this doesnt seems to be supported now?
# meta: {'languages': ['python']}
# tags: ["important_tag"]


require-dbt-version: [">=1.0.0", "<2.0.0"]
version: 0.1.0
