config-version: 2

name: source_config_project
profile: source_config_project

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

seeds:
  localdep:
    enabled: true
  quote_columns: false
sources:
  enabled: true
  # quoting:
  #   database: False
  #   schema: False
  #   identifier: False
  #   column: False
  # freshness:
  #   error_after: {count: 10, period: hour}
  #   warn_after: {count: 20, period: hour}
  # loader: "project_loader"
  # loaded_at_field: project_column
  # database: project_database  # note: this won't work unless it's real
  # schema: project_schema
  # meta: {'source': ['project']}
  # tags: ["project_tag"]


require-dbt-version: [">=1.0.0", "<2.0.0"]
version: 0.1.0
