version: 2

sources:
  - name: generate_sources
    description: Sources loaded from seeds in another project # not a config
    schema: dbt_sources  # property version
    # config:
    #   enabled: True
    #   quoting: {dict}
    #   freshness: {dict}
    #   loader: ...
    #   loaded_at_field: ...
    #   database: ... # or 'project' in dbt-bigquery
    #   schema: dbt_sources # or 'dataset' in dbt-bigquery
    #   identifier: ... # this is like an alias for alias
    #   meta: {dict}
    #   tags: ...
    tables:
      - name: raw_customers
        # config: # all the same stuff as above. these take precedence for specific tables
        #   enabled: False
        #   quoting: {dict}
        #   freshness: {dict}
        #   loader: ...
        #   loaded_at_field: ...
        #   database: ... # or 'project' in dbt-bigquery
        #   schema: ... # or 'dataset' in dbt-bigquery
        #   identifier: ... # this is like an alias for alias
        #   meta: {dict}
        #   tags: ...
        description: Raw customer data # not a config
        # tests: ... # not a config
        # columns: ... # not a config
      #   columns:
      # - name: order_id
      #   tests:
      #     - unique
      #     - not_null
      - name: raw_orders
      - name: raw_payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
