version: 2
sources:
  - name: my_source
    overrides: localdep
    schema: "{{ target.schema }}"
    database: "{{ target.database }}"
    freshness:
      error_after: {count: 3, period: day}
    tables:
      - name: my_table
        identifier: my_package_seed
        # on the override, the "color" column is only unique, it can be null!
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: color
            tests:
              - unique
      - name: my_other_table
        identifier: my_package_other_seed

# same as above with all properties defined as configs instead
# sources:
#   - name: my_source
#     overrides: localdep
#     config:
#       schema: "{{ target.schema }}"
#       database: "{{ target.database }}"
#       freshness:
#         error_after: {count: 3, period: day}
#     tables:
#       - name: my_table
#         config:
#           identifier: my_package_seed
#         # on the override, the "color" column is only unique, it can be null!
#         columns:
#           - name: id
#             tests:
#               - not_null
#               - unique
#           - name: color
#             tests:
#               - unique
#       - name: my_other_table
#         config:
#           identifier: my_package_other_seed
